services:
  mosquitto:
    image: eclipse-mosquitto
    network_mode: host
    restart: always
    volumes:
      - /etc/mpp-solar/mosquitto/config:/mosquitto/config
      - /etc/mpp-solar/mosquitto/data:/mosquitto/data
      - /etc/mpp-solar/mosquitto/log:/mosquitto/log

  mppsolar:
    build: .
    image: docker-mppsolar
    network_mode: host
    restart: always
    devices:
     - /dev/hidraw0:/dev/hidraw0
    volumes:
    #Bind over the configuration
      - type: bind
        source: /etc/mpp-solar/
        target: /etc/mpp-solar
    entrypoint:
      - mpp-solar
      - -C
      - /etc/mpp-solar/mpp-solar.conf #Available due to volume binding above
      - --daemon
    depends_on:
      - mosquitto
